[versions]
core-ktx = "1.9.0"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.0"
compose-bom = "2023.03.00"

[libraries.android-gradle]
version = "8.1.2"
module = "com.android.tools.build:gradle"

[libraries.core-ktx]
version.ref = "core-ktx"
group = "androidx.core"
name = "core-ktx"

[libraries.lifecycle-runtime-ktx]
version.ref = "lifecycle-runtime-ktx"
module = "androidx.lifecycle:lifecycle-runtime-ktx"

[libraries.activity-compose]
version.ref = "activity-compose"
module = "androidx.activity:activity-compose"

[libraries.compose-bom]
version.ref = "compose-bom"
module = "androidx.compose:compose-bom"

[libraries.compose-ui]
group = "androidx.compose.ui"
name = "ui"

[libraries.compose-ui-graphics]
group = "androidx.compose.ui"
name = "ui-graphics"

[libraries.compose-foundation]
module = "androidx.compose.foundation:foundation"

[libraries.androidx-appcompat]
version = "1.6.1"
module = "androidx.appcompat:appcompat"

[bundles]
androidx = ["androidx-appcompat", "core-ktx", "lifecycle-runtime-ktx", "activity-compose"]
compose = ["compose-ui", "compose-ui-graphics", "compose-foundation"]
