[versions]
regolith = "1.1.0"
ink-ui = "0.3.1"
watermelon = "1.4.0"

[libraries.kimchi-core]
version = "2.0.3"
module = "com.inkapplications.kimchi:core"

[libraries.regolith-init]
version.ref = "regolith"
module = "com.inkapplications.regolith:init"

[libraries.regolith-processes]
version.ref = "regolith"
module = "com.inkapplications.regolith:processes"

[libraries.regolith-resources]
version.ref = "regolith"
module = "com.inkapplications.regolith:resources"

[libraries.ui-structures]
version.ref = "ink-ui"
module = "com.inkapplications.ui:structures"

[libraries.ui-compose]
version.ref = "ink-ui"
module = "com.inkapplications.ui:render-compose"

[libraries.spondee-units]
version = "1.4.0"
module = "com.inkapplications.spondee:units"

[libraries.watermelon-datetime]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:datetime"

[libraries.watermelon-android]
version.ref = "watermelon"
module = "com.inkapplications.watermelon:android"

[bundles]
regolith = ["regolith-init", "regolith-processes", "regolith-resources"]
